"""Write `.env.example` from the declared contract in `app/config.py`.

`.env.example` is not a courtesy file. The README tells a reader to copy
it, so it is the setup instructions, and a submission is required to
ship instructions that work. It drifted from the code once already: it
documented Gmail keys the running system no longer had, and omitted the
reviewer password and every AWS key, including the two the identity gate
requires. Anyone following it got a system that could not reach Bedrock.

So it is generated, never edited. `tests/env_contract_smoke.py` fails if
the file on disk differs from what this script would write.

Usage:

    python scripts/generate_env_example.py          # write the file
    python scripts/generate_env_example.py --check  # exit 1 if stale
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from app import config  # noqa: E402

TARGET = REPO_ROOT / ".env.example"

HEADER = """\
# Generated by scripts/generate_env_example.py. Do not edit by hand.
#
# Copy this file to .env and fill in the values. .env is gitignored and
# must never be committed. Keys marked REQUIRED have no default: the
# software refuses to run the affected part rather than guessing.
#
# Nothing here is a real credential. The AWS account id and principal
# below are placeholders; substitute your own.
"""


def render():
    """Return the full text of `.env.example`."""
    lines = [HEADER]

    for group in config.GROUP_ORDER:
        keys = [k for k in config.CONTRACT if k.group == group]

        if not keys:
            continue

        lines.append("")
        lines.append("# " + "-" * 66)
        lines.append(f"# {config.GROUP_TITLES[group]}")
        lines.append("# " + "-" * 66)

        for key in keys:
            lines.append("")
            status = "REQUIRED" if key.required else "optional"
            lines.append(f"# [{status}] {key.note}")
            lines.append(f"{key.name}={key.example}")

    lines.append("")
    lines.append("# " + "-" * 66)
    lines.append(
        "# Deliberately absent: "
        + ", ".join(sorted(config.DELIBERATELY_NOT_IN_CONTRACT))
        + "."
    )
    lines.append(
        "# These authorise a real outbound send. They are read straight"
    )
    lines.append(
        "# from the process environment so that sending real mail is"
    )
    lines.append(
        "# always a deliberate act in a shell, never inherited from a"
    )
    lines.append("# file that someone copied.")
    lines.append("")

    return "\n".join(lines)


def main():
    wanted = render()
    check_only = "--check" in sys.argv

    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None

    if current == wanted:
        print(f"{TARGET.name} is current ({len(config.CONTRACT)} keys).")
        return 0

    if check_only:
        print(
            f"{TARGET.name} is STALE. "
            f"Run: python scripts/generate_env_example.py"
        )
        return 1

    TARGET.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET.name} ({len(config.CONTRACT)} keys).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
